# Generated by Django 5.1.6 on 2025-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
    ]
