# Generated by Django 5.1.6 on 2025-02-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_rssfeed_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('PYTHON', 'Python'), ('DEVOPS', 'DevOps'), ('NEWS', 'News'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
    ]
