# Generated by Django 5.1.6 on 2025-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_rssfeed_category_alter_rssfeed_feed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='category',
            field=models.CharField(choices=[('ai', 'Artificial Intelligence'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('python', 'Python'), ('devops', 'DevOps'), ('news', 'News'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='feed_type',
            field=models.CharField(choices=[('article', 'Article Feed'), ('youtube', 'YouTube Feed')], default='article', max_length=10),
        ),
    ]
