# Generated by Django 5.1.6 on 2025-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_alter_content_image_url_alter_rssfeed_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['published_date', 'category'], name='feeds_conte_publish_2011b6_idx'),
        ),
    ]
